name: win_dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - conda-forge::faiss-cpu
  - menuinst
  - pytorch::torchtext
  - pip
  - ipywidgets
  - ipympl
  - cython
  - notebook
  - jupyterlab
  - unqlite
  - conda-forge::torchinfo
  - conda-forge::imbalanced-learn
  - conda-forge::scikit-learn
  - conda-forge::jupytext
  - pip:
    - medspacy
    - git+https://github.com/medspacy/medspacy_io.git
    - anywidget
    - beautifulsoup4
    - bioc
    - simpletransformers
    - nltk
    - numba
    - numpy
    - sqlalchemy
    - ipympl
    - numexpr
    - statsmodels
    - bioc==2.0
    - tqdm
    - spacy
    - tensorboard
    - pytest
    - setuptools
    - wheel
    - scipy
    - joblib
    - jupyterlab-widgets
    - matplotlib
    - loguru
    - gensim
    - python-dateutil
    - pyodbc
    - xgboost
    - xlrd
    - openpyxl
    - flask
    - flask-restful
    - keras
    - loguru
    - lxml    
    - markdown
    - matplotlib
    - mlflow
    - multiprocess
    - murmurhash      
    - oauthlib
    - openpyxl    
    - optimum
    - optuna
    - pandas
    - plotly
    - preshed
    - protobuf
    - py4j
    - install-jdk
    - JPype1
    - py7zr
    - pydantic
    - seaborn
    - bokeh
    - sqlparse
    - statsmodels
    - tokenizers
    - torchmetrics
    - unidecode
    - wandb
    - grpcio
    - protobuf
    - grpcio-tools
    - googleapis-common-protos
    - ninja
    - pyyaml
    - requests
    - langchain
    - langchain-core
    - langchain-community
    - langchain-experimental
    - langgraph
    - langchain-cli
    - langsmith
    - langchain-openai
    - langchain-huggingface
    - langchain-anthropic
    - langserve[all]
    - dask[complete]
    - ray[data,train,tune,serve]
    - uv
    - prefect
    - Whoosh
    - mcp

