name: win_scale_gpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - conda-forge::faiss-gpu
  - pytorch::pytorch-cuda=12.4
  - nvidia/label/cuda-12.4.0::cuda-nvcc
  - conda-forge:cudnn
  - menuinst
  - pytorch::torchtext
  - pip
  - ipywidgets
  - ipympl
  - cython
  - notebook
  - jupyterlab
  - unqlite
  - conda-forge::torchinfo
  - conda-forge::imbalanced-learn
  - conda-forge::scikit-learn
  - conda-forge::jupytext
  - pip:
    - medspacy
    - git+https://github.com/medspacy/medspacy_io.git
    - anywidget
    - accelerate
    - beautifulsoup4
    - bioc
    - bitsandbytes
    - transformers>=4.31.0
    - simpletransformers
    - nltk
    - numba
    - numpy
    - sqlalchemy
    - ipympl
    - numexpr
    - statsmodels
    - bioc==2.0
    - tqdm
    - spacy
    - tensorboard
    - pytest
    - setuptools
    - wheel
    - scipy
    - joblib
    - jupyterlab-widgets
    - loguru
    - gensim
    - python-dateutil
    - pyodbc
    - xgboost
    - xlrd
    - flask
    - flask-restful
    - keras
    - loguru
    - lxml    
    - markdown
    - matplotlib
    - mlflow
    - multiprocess
    - murmurhash  
    - nvgpu    
    - oauthlib
    - openpyxl    
    - optimum
    - optuna
    - pandas
    - plotly
    - preshed
    - protobuf
    - psutil
    - py4j
    - install-jdk
    - JPype1
    - py7zr
    - pydantic
    - seaborn
    - bokeh
    - sqlalchemy<2
    - sqlparse
    - statsmodels
    - tokenizers
    - torchmetrics
    - torchserve
    - torch-model-archiver
    - torch-workflow-archiver    
    - torch-ort
    - onnxruntime-gpu
    - unidecode
    - wandb
    - grpcio
    - protobuf
    - grpcio-tools
    - googleapis-common-protos
    - ninja
    - pynvml
    - pyyaml
    - requests
    - langchain
    - langchain-core
    - langchain-community
    - langchain-experimental
    - langgraph
    - langchain-cli
    - langsmith
    - langchain-openai
    - langchain-huggingface
    - langchain-anthropic
    - langserve[all]
    - dask[complete]
    - ray[data,train,tune,serve]
    - uv
    - prefect
    - Whoosh
    - mcp

